import { Roboto } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import { Toaster } from "react-hot-toast";
import { RoleProvider } from "@/context/RoleContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: '400'
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <SessionWrapper>
          <RoleProvider>
           {children}
          </RoleProvider>
          <Toaster position="bottom-right" />
        </SessionWrapper>
      </body>
    </html>
  );
}
